---
os: linux
dist: xenial  # Python3.7 virtualenv is available only on Travis Xenial VMs.
language: go
sudo: true
go:
  - "1.16"
env:
  - GO111MODULE=on
before_install:
  - true # just skip
install:
  - true # just skip
script:
  - go test -v
after_success:
  - true # just skip